---
title: "Homework07"
author: "Andres Gonzalez"
date: "2023-03-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
```

https://github.com/Gandres16/DS202


```{r}
data(happy, package="productplots")
head(happy)
```
```{r}
HAPPY <- readRDS("data/HAPPY.rds")
```

```{r}
HAPPY <- replace(HAPPY, HAPPY == "IAP", NA)
HAPPY <- replace(HAPPY, HAPPY == "DK", NA)
HAPPY <- replace(HAPPY, HAPPY == "NA", NA)
head(HAPPY)
```

```{r}
HAPPY <- HAPPY %>% mutate(
  age = replace(AGE, AGE == "89 OR OLDER", 89),
  age = as.numeric(age)
) %>% select(-AGE)
HAPPY %>% ggplot(aes(x = age)) + geom_histogram(binwidth=1)
```

```{r}
HAPPY$SEX = factor(HAPPY$SEX, levels = c("MALE", "FEMALE"))
ggplot(data = HAPPY, aes(x= SEX)) + geom_bar()
```

```{r}
HAPPY$MARITAL = factor(HAPPY$MARITAL, levels = c("NEVER MARRIED", "MARRIED", "SEPERATED", "DIVORCED", "WIDOWED"))
ggplot(data = HAPPY, aes(x= MARITAL)) + geom_bar()
```


```{r}
HAPPY$HAPPY = factor(HAPPY$HAPPY, levels = c("NOT TOO HAPPY", "PRETTY HAPPY", "VERY HAPPY"))
ggplot(data = HAPPY, aes(x= HAPPY)) + geom_bar()
```

```{r}
HAPPY$HEALTH= factor(HAPPY$HEALTH,levels= c("IAP", "POOR", "FAIR", "GOOD", "EXCELLENT", "DK"))
ggplot(data = HAPPY, aes(x= HEALTH)) + geom_bar()
```

```{r}
HAPPY$DEGREE= factor(HAPPY$DEGREE,levels= c("LT HIGH SCHOOL", "HIGH SCHOOL", "BACHELOR", "GRADUATE"))
ggplot(data = HAPPY, aes(x= DEGREE)) + geom_bar()
```


```{r}
HAPPY$FINRELA= factor(HAPPY$FINRELA,levels= c("BELOW AVERAGE", "AVERAGE", "ABOVE AVERAGE"))
ggplot(data = HAPPY, aes(x= FINRELA)) + geom_bar()
```


```{r}
HAPPY$PARTYID= factor(HAPPY$PARTYID,levels= c("STRONG DEMOCRAT", "IND, NEAR DEM", "NOT STR DEMOCRAT", "INDEPENDENT", "NOT STR REPUBLICAN", "IND, NEAR REP", "STRONG REPULICAN", "OTHER PARTY"))
ggplot(data = HAPPY, aes(x= PARTYID)) + geom_bar() + coord_flip()
```


```{r}
library(ggplot2)
ggplot(HAPPY, aes(x=HAPPY, y=PARTYID, color=SEX)) + geom_jitter()
```

we can see that both parties are equally not too happy, pretty happy, and very happy. People with no party had the least amount of people in the not too happy category. there was an equal amount of sexes in each party as well.